[workspace]
members = [
    "crates/engine",
    "crates/game",
    "crates/mapgen",
    "crates/tiled",
    "crates/rpg-godot",
    "crates/rpg-tools",
    "crates/helpers",
    "sixel-console",
    "sdl2-console"
]
exclude = ["tdeck", ]
resolver = "2"

[workspace.dependencies]
# Error handling
thiserror = "2"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

# Hashing / PRNG
sha3 = "0.12"

# Lua scripting
mlua = { version = "0.11", features = ["lua54", "vendored"] }

# TMX / XML
quick-xml = { version = "0.37", features = ["serialize"] }

# Serialization
serde = { version = "1", features = ["derive", "alloc"] }
serde_json = "1"

# Godot
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }

clap = { version = "4.6", features = ["derive"] }
