[workspace]
members = [
    "crates/ai",
    "crates/engine",
    "crates/mapgen",
    "crates/tiled",
    "crates/rpg-tools",
    "crates/helpers",
    "bevy-console"
]

resolver = "3"

[workspace.dependencies]
# Error handling
thiserror = "2"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

# Hashing / PRNG
sha3 = "0.12"

# Lua scripting
mlua = { version = "0.11", features = ["lua54", "vendored"] }

# TMX / XML
quick-xml = { version = "0.37", features = ["serialize"] }

# Serialization
serde = { version = "1", features = ["derive", "alloc"] }
serde_json = "1"
serde_yaml = "0.9"

clap = { version = "4.6", features = ["derive"] }
