//! Map assembler — orchestrates chunk generation, stitching, and validation.
//!
//! [`MapAssembler`] is the primary entry point for producing a fully assembled
//! and validated [`GameMap`].  It:
//! 1. Derives per-chunk seeds from the map seed phrase.
//! 2. Generates each chunk in row-major order via a Lua generator script.
//! 3. Stitches chunk boundary seams.
//! 4. Optionally validates the map with a Lua validator script.
//! 5. Optionally evaluates the map with a Lua evaluator script.

use std::path::PathBuf;

use tracing::{debug, info, instrument, warn};

use rpg_engine::map::chunk::ChunkCoord;
use rpg_engine::map::game_map::GameMap;
use rpg_engine::rng::keccak256;

use crate::chunk_generator::ChunkGenerator;
use crate::error::Error;
use crate::evaluator::MapEvaluator;
use crate::stitcher::Stitcher;
use crate::validator::MapValidator;

// ─── MapConfig ────────────────────────────────────────────────────────────────

/// Configuration for map generation.
#[derive(Debug, Clone)]
pub struct MapConfig {
    /// Number of chunks along the horizontal axis.
    pub chunks_wide: u32,
    /// Number of chunks along the vertical axis.
    pub chunks_tall: u32,
    /// Human-readable seed phrase.  Hashed to a `[u8; 32]` via Keccak256.
    pub seed: String,
    /// Path to the Lua chunk generator script.
    pub generator_script: PathBuf,
    /// Optional path to the Lua evaluator script.
    pub evaluator_script: Option<PathBuf>,
    /// Optional path to the Lua validator script.
    pub validator_script: Option<PathBuf>,
}

impl MapConfig {
    /// Creates a minimal config for a 3×3 chunk map (96×96 tiles).
    pub fn default_3x3(seed: impl Into<String>, generator_script: impl Into<PathBuf>) -> Self {
        Self {
            chunks_wide: 3,
            chunks_tall: 3,
            seed: seed.into(),
            generator_script: generator_script.into(),
            evaluator_script: None,
            validator_script: None,
        }
    }

    /// Adds a validator script path to the config.
    pub fn with_validator(mut self, path: impl Into<PathBuf>) -> Self {
        self.validator_script = Some(path.into());
        self
    }

    /// Adds an evaluator script path to the config.
    pub fn with_evaluator(mut self, path: impl Into<PathBuf>) -> Self {
        self.evaluator_script = Some(path.into());
        self
    }
}

// ─── MapAssembler ─────────────────────────────────────────────────────────────

/// Assembles a complete [`GameMap`] from chunks generated by a Lua script.
pub struct MapAssembler {
    config: MapConfig,
    generator: ChunkGenerator,
    evaluator: Option<MapEvaluator>,
    validator: Option<MapValidator>,
    /// Derived 32-byte map seed (Keccak256 of `config.seed`).
    map_seed: [u8; 32],
}

impl MapAssembler {
    /// Creates a new [`MapAssembler`] from the given configuration.
    ///
    /// Loads all Lua scripts up-front so that script errors are reported
    /// before generation begins.
    ///
    /// # Errors
    /// Returns [`Error::ScriptLoad`] if any script file cannot be loaded,
    /// or [`Error::Io`] if a script file cannot be read.
    pub fn new(config: MapConfig) -> Result<Self, Error> {
        let map_seed = keccak256(&config.seed);
        let generator = ChunkGenerator::from_script(&config.generator_script)?;

        let evaluator = config
            .evaluator_script
            .as_deref()
            .map(MapEvaluator::from_script)
            .transpose()?;

        let validator = config
            .validator_script
            .as_deref()
            .map(MapValidator::from_script)
            .transpose()?;

        info!(
            seed = %config.seed,
            chunks_wide = config.chunks_wide,
            chunks_tall = config.chunks_tall,
            "map assembler initialised"
        );

        Ok(Self {
            config,
            generator,
            evaluator,
            validator,
            map_seed,
        })
    }

    /// Returns the derived 32-byte map seed.
    pub fn map_seed(&self) -> &[u8; 32] {
        &self.map_seed
    }

    /// Generates a map without running the validator.
    ///
    /// Runs all chunk generators and the stitcher, but skips validation even
    /// if a validator script was provided.
    ///
    /// # Errors
    /// Returns [`Error::LuaExecution`] if any chunk generator script fails,
    /// or an engine error if map assembly fails.
    #[instrument(skip(self))]
    pub fn generate(&self) -> Result<GameMap, Error> {
        let cw = self.config.chunks_wide;
        let ct = self.config.chunks_tall;
        let total = cw * ct;

        info!(chunks = total, "starting map generation");
        let mut chunks = Vec::with_capacity(total as usize);

        for cy in 0..ct {
            for cx in 0..cw {
                let coord = ChunkCoord::new(cx, cy);
                debug!(cx, cy, "generating chunk");
                let chunk = self.generator.generate(coord, &self.map_seed)?;
                chunks.push(chunk);
            }
        }

        let mut map = GameMap::new(cw, ct, chunks, self.map_seed)?;

        info!("stitching chunk boundaries");
        Stitcher::stitch(&mut map)?;

        if let Some(ev) = &self.evaluator {
            let score = ev.evaluate(&map)?;
            info!(score, "map evaluated");
        }

        Ok(map)
    }

    /// Generates a map and then validates it.
    ///
    /// If a validator script was provided and the map fails validation, returns
    /// [`Error::ValidationFailed`].  If no validator was provided, behaves
    /// identically to [`generate`](Self::generate).
    ///
    /// # Errors
    /// Returns [`Error::ValidationFailed`] if the map does not satisfy the
    /// Lua validation rules, or any error from [`generate`](Self::generate).
    pub fn generate_validated(&self) -> Result<GameMap, Error> {
        let map = self.generate()?;

        if let Some(v) = &self.validator {
            let result = v.validate(&map)?;
            if !result.is_valid() {
                let reason = result.reason.unwrap_or_default();
                warn!(%reason, "generated map failed validation");
                return Err(Error::ValidationFailed(reason));
            }
            info!("map passed validation");
        }

        Ok(map)
    }

    /// Generates up to `attempts` maps, returning the first one that passes
    /// validation.
    ///
    /// If no attempt produces a valid map, returns the last [`Error::ValidationFailed`].
    /// If no validator is configured, the first map is returned immediately.
    ///
    /// # Arguments
    /// * `attempts` - Maximum number of generation attempts.
    ///
    /// # Errors
    /// Returns [`Error::ValidationFailed`] if all attempts fail validation,
    /// or any other error from generation.
    pub fn generate_best_of(&self, attempts: u32) -> Result<GameMap, Error> {
        let mut last_err: Option<Error> = None;

        for attempt in 0..attempts {
            debug!(attempt, "generation attempt");
            match self.generate_validated() {
                Ok(map) => {
                    info!(attempt, "valid map found");
                    return Ok(map);
                }
                Err(Error::ValidationFailed(reason)) => {
                    warn!(attempt, %reason, "attempt failed validation, retrying");
                    last_err = Some(Error::ValidationFailed(reason));
                }
                Err(e) => return Err(e),
            }
        }

        Err(last_err.unwrap_or_else(|| Error::ValidationFailed("no attempts made".into())))
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use rpg_engine::map::chunk::CHUNK_SIZE;
    use crate::test_utils::init_tracing;

    /// Inline generator script: fills all tiles with grass.
    const GRASS_GENERATOR: &str = r#"
        return function(rng, x, y)
            local tiles = {}
            for i = 1, 32 * 32 do tiles[i] = "meadow" end
            return tiles
        end
    "#;

    /// Inline generator script: fills all tiles with water (will fail validation).
    const WATER_GENERATOR: &str = r#"
        return function(rng, x, y)
            local tiles = {}
            for i = 1, 32 * 32 do tiles[i] = "water" end
            return tiles
        end
    "#;

    /// Inline validator: requires >50% passable terrain.
    const PASSABLE_VALIDATOR: &str = r#"
        return function(map)
            local pass = 0
            for _, k in ipairs(map.tiles) do
                if k ~= "water" and k ~= "mountain" then pass = pass + 1 end
            end
            if pass / #map.tiles < 0.50 then
                return false, "too little passable terrain"
            end
            return true, nil
        end
    "#;

    fn write_temp_script(name: &str, content: &str) -> PathBuf {
        let dir = std::env::temp_dir();
        let path = dir.join(format!("rpg_test_{name}.lua"));
        std::fs::write(&path, content).unwrap();
        path
    }

    fn make_assembler(generator: &str) -> MapAssembler {
        let gen_path = write_temp_script("gen", generator);
        let config = MapConfig::default_3x3("test-seed", gen_path);
        MapAssembler::new(config).unwrap()
    }

    #[test]
    fn generates_correct_dimensions() {
        init_tracing();
        let asm = make_assembler(GRASS_GENERATOR);
        let map = asm.generate().unwrap();
        assert_eq!(map.chunks_wide(), 3);
        assert_eq!(map.chunks_tall(), 3);
        assert_eq!(map.tile_width(), 3 * CHUNK_SIZE as u32);
        assert_eq!(map.tile_height(), 3 * CHUNK_SIZE as u32);
    }

    #[test]
    fn same_seed_produces_same_map() {
        init_tracing();
        let gen_path = write_temp_script("gen_det", GRASS_GENERATOR);
        let config = MapConfig::default_3x3("deterministic", gen_path);
        let asm = MapAssembler::new(config).unwrap();

        let map_a = asm.generate().unwrap();
        let map_b = asm.generate().unwrap();

        for (ca, cb) in map_a.chunks().iter().zip(map_b.chunks()) {
            assert_eq!(ca.tiles(), cb.tiles());
        }
    }

    #[test]
    fn validation_passes_for_grass_map() {
        init_tracing();
        let gen_path = write_temp_script("gen_valid", GRASS_GENERATOR);
        let val_path = write_temp_script("val_valid", PASSABLE_VALIDATOR);
        let config = MapConfig::default_3x3("valid-seed", gen_path).with_validator(val_path);
        let asm = MapAssembler::new(config).unwrap();

        let map = asm.generate_validated();
        assert!(map.is_ok(), "grass map should pass validation: {map:?}");
    }

    #[test]
    fn validation_fails_for_water_map() {
        init_tracing();
        let gen_path = write_temp_script("gen_water", WATER_GENERATOR);
        let val_path = write_temp_script("val_water", PASSABLE_VALIDATOR);
        let config = MapConfig::default_3x3("water-seed", gen_path).with_validator(val_path);
        let asm = MapAssembler::new(config).unwrap();

        let result = asm.generate_validated();
        assert!(
            matches!(result, Err(Error::ValidationFailed(_))),
            "all-water map should fail validation, got: {result:?}"
        );
    }

    #[test]
    fn map_seed_is_deterministic() {
        init_tracing();
        let gen_path = write_temp_script("gen_seed", GRASS_GENERATOR);
        let config = MapConfig::default_3x3("seed-phrase", gen_path);
        let asm = MapAssembler::new(config).unwrap();
        let seed_a = *asm.map_seed();

        let gen_path2 = write_temp_script("gen_seed2", GRASS_GENERATOR);
        let config2 = MapConfig::default_3x3("seed-phrase", gen_path2);
        let asm2 = MapAssembler::new(config2).unwrap();
        assert_eq!(seed_a, *asm2.map_seed());
    }
}
