//! Build information module.
//!
//! Provides compile-time version info generated by the build script.
//! `BUILD_SRC_HASH` changes whenever any `.rs` source file changes,
//! even without a new git commit — making every modified build uniquely
//! identifiable.

/// Short git commit hash (e.g., `"a1b2c3d"`).
pub const GIT_HASH: &str = env!("BUILD_GIT_HASH");

/// Git commit timestamp (e.g., `"2026-04-01 12:34:56 +0300"`).
pub const GIT_TIMESTAMP: &str = env!("BUILD_GIT_TIMESTAMP");

/// Unix timestamp of when this binary was compiled.
pub const BUILD_NUMBER: &str = env!("BUILD_NUMBER");

/// Build profile (`"debug"` or `"release"`).
pub const BUILD_PROFILE: &str = env!("BUILD_PROFILE");

/// FNV-1a hash of all `.rs` source files at compile time (8 hex chars).
/// Changes whenever source code changes, even without a new git commit.
pub const SRC_HASH: &str = env!("BUILD_SRC_HASH");

/// Short build ID shown in the UI and console: `{git_hash}-{src_hash}`.
///
/// Example: `"bd3e4b4-a3f0c1b2"` — the git part identifies the commit,
/// the src part identifies uncommitted code changes.
pub fn version_string() -> String {
    format!("{}-{} ({})", GIT_HASH, SRC_HASH, BUILD_PROFILE)
}

/// Full build info for logs.
pub fn build_info() -> String {
    format!(
        "Build: {} | Git: {} | Src: {} | Profile: {} | Committed: {}",
        BUILD_NUMBER, GIT_HASH, SRC_HASH, BUILD_PROFILE, GIT_TIMESTAMP
    )
}
