//! Shared `embedded-graphics` rendering for the gameplay map view.

use alloc::{format, string::String, string::ToString, vec, vec::Vec};

use embedded_graphics::draw_target::DrawTarget;
use embedded_graphics::mono_font::ascii::FONT_6X10;
use embedded_graphics::mono_font::MonoTextStyle;
use embedded_graphics::pixelcolor::PixelColor;
use embedded_graphics::prelude::{Point, Primitive, Size};
use embedded_graphics::primitives::{PrimitiveStyle, Rectangle};
use embedded_graphics::text::Text;
use embedded_graphics::{Drawable, Pixel};
use engine::hero::HeroId;
use engine::map::game_map::MapCoord;
use engine::map::tile::Tiles;

use crate::app::{
    AppScreen, MapViewScreen, APP_TITLE, MAP_LIST_FOOTER, MAP_LIST_TITLE, SAVE_LIST_FOOTER,
    SAVE_LIST_TITLE, SPLASH_FOOTER, SPLASH_OPTIONS,
};
use crate::info_overlay::InfoOverlay;
use crate::list::ListScreen;
use crate::map_view::MapViewApp;
use crate::save_overlay::SaveOverlay;
use crate::splash::SplashScreen;
use crate::turn_overlay::EndTurnOverlay;

const EMPTY_TILE: u32 = u32::MAX;

// Unified tile atlas embedded at compile time.
// Format: b"RPGT" + u8 tile_w + u8 tile_h + u32 count LE, then count × mask_bytes.
// Generated by: cargo run -p rpg-tools --bin pack-tiles
const TILES_BIN: &[u8] = include_bytes!("../../../assets/tiles.bin");
const ATLAS_HEADER: usize = 10; // 4 magic + 1 w + 1 h + 4 count LE

const TILESET_TILE_W: usize = 16;
const TILESET_TILE_H: usize = 16;
const TILESET_MASK_BYTES: usize = (TILESET_TILE_W * TILESET_TILE_H).div_ceil(8);

// Grass tile indices within the atlas (tiles 5, 6, 7 from monochrome-transparent_packed.png).
const GRASS_INDICES: [usize; 3] = [5, 6, 7];
const GRASS_TILE_COUNT: usize = GRASS_INDICES.len();

const FOREST_INDICES: [usize; 6] = [49, 50, 51, 52, 53, 54];
const FOREST_TILE_COUNT: usize = FOREST_INDICES.len();

// Water tile indices from 2_water.png (5 tiles at 1078..1082).
const WATER_BASE: usize = 1078;
const WATER_FULL: usize = WATER_BASE; // tile 0: full water rectangle
const WATER_SHORE_LL: usize = WATER_BASE + 1; // tile 1: shore, lower-left half of W edge
const WATER_CORNER_OUTER: usize = WATER_BASE + 3; // tile 3: outer corner, upper-left
const WATER_CORNER_INNER: usize = WATER_BASE + 4; // tile 4: inner corner, upper-left

// Mountain tile indices from 3_mountains.png (5 tiles at 1083..1087).
const MOUNTAIN_BASE: usize = 1083;
const MOUNTAIN_FULL: usize = MOUNTAIN_BASE;
const MOUNTAIN_SHORE_LL: usize = MOUNTAIN_BASE + 1;
const MOUNTAIN_CORNER_OUTER: usize = MOUNTAIN_BASE + 3;
const MOUNTAIN_CORNER_INNER: usize = MOUNTAIN_BASE + 4;

type WaterMask = [u8; TILESET_MASK_BYTES];

const TILE_WIDTH: u32 = 32;
const TILE_HEIGHT: u32 = 32;

fn tile_atlas_mask(tile_idx: usize) -> &'static [u8] {
    let start = ATLAS_HEADER + tile_idx * TILESET_MASK_BYTES;
    &TILES_BIN[start..start + TILESET_MASK_BYTES]
}

fn grass_mask(grass_idx: usize) -> &'static [u8] {
    tile_atlas_mask(GRASS_INDICES[grass_idx])
}

fn forest_mask(forest_idx: usize) -> &'static [u8] {
    tile_atlas_mask(FOREST_INDICES[forest_idx])
}

fn get_tile_mask_arr(idx: usize) -> WaterMask {
    let mut arr = [0u8; TILESET_MASK_BYTES];
    arr.copy_from_slice(tile_atlas_mask(idx));
    arr
}

fn mask_pixel_arr(m: &WaterMask, x: usize, y: usize) -> bool {
    let bit = y * TILESET_TILE_W + x;
    (m[bit / 8] >> (7 - bit % 8)) & 1 != 0
}

fn rotate_cw90(m: &WaterMask) -> WaterMask {
    // pixel (x, y) → (N-1-y, x) where N = TILESET_TILE_W = 16
    let n = TILESET_TILE_W;
    let mut out = [0u8; TILESET_MASK_BYTES];
    for y in 0..n {
        for x in 0..n {
            if mask_pixel_arr(m, x, y) {
                let nx = n - 1 - y;
                let ny = x;
                let bit = ny * n + nx;
                out[bit / 8] |= 1 << (7 - bit % 8);
            }
        }
    }
    out
}

fn and_mask(mut a: WaterMask, b: &WaterMask) -> WaterMask {
    for i in 0..TILESET_MASK_BYTES {
        a[i] &= b[i];
    }
    a
}

// Neighbor bits: bit0=N, bit1=NE, bit2=E, bit3=SE, bit4=S, bit5=SW, bit6=W, bit7=NW
// 1 = neighbor is water, 0 = neighbor is land or out-of-bounds
/// Computes 8-neighbor bitmask for terrain autotiling.
/// Bits (0..7) = N, NE, E, SE, S, SW, W, NW; bit=1 means neighbor matches `target`.
fn terrain_neighbor_bits(
    map: &engine::map::game_map::GameMap,
    coord: MapCoord,
    target: engine::map::tile::Tiles,
) -> u8 {
    let matcher = |cx: i32, cy: i32| -> bool {
        if cx < 0 || cy < 0 {
            return false;
        }
        let c = MapCoord::new(cx as u32, cy as u32);
        map.get_tile(c).is_ok_and(|t| t.kind == target)
    };
    let x = coord.x as i32;
    let y = coord.y as i32;
    let n = matcher(x, y - 1) as u8;
    let ne = matcher(x + 1, y - 1) as u8;
    let e = matcher(x + 1, y) as u8;
    let se = matcher(x + 1, y + 1) as u8;
    let s = matcher(x, y + 1) as u8;
    let sw = matcher(x - 1, y + 1) as u8;
    let w = matcher(x - 1, y) as u8;
    let nw = matcher(x - 1, y - 1) as u8;
    n | (ne << 1) | (e << 2) | (se << 3) | (s << 4) | (sw << 5) | (w << 6) | (nw << 7)
}

/// Autotile composite mask: `bits` describes neighbors matching the terrain.
/// `land()` returns true when the neighbor does *not* match (== land).
fn compute_terrain_composite(
    bits: u8,
    full_tile: usize,
    shore_ll: usize,
    corner_outer: usize,
    corner_inner: usize,
) -> WaterMask {
    let land = |bit: u8| (bits & bit) == 0;
    let n = land(0x01);
    let ne = land(0x02);
    let e = land(0x04);
    let se = land(0x08);
    let s = land(0x10);
    let sw = land(0x20);
    let w = land(0x40);
    let nw = land(0x80);

    let ll = get_tile_mask_arr(shore_ll);
    let ul = get_tile_mask_arr(shore_ll + 1);
    let co = get_tile_mask_arr(corner_outer);
    let ci = get_tile_mask_arr(corner_inner);
    let ll90 = rotate_cw90(&ll);
    let ll180 = rotate_cw90(&ll90);
    let ll270 = rotate_cw90(&ll180);
    let ul90 = rotate_cw90(&ul);
    let ul180 = rotate_cw90(&ul90);
    let ul270 = rotate_cw90(&ul180);
    let co90 = rotate_cw90(&co);
    let co180 = rotate_cw90(&co90);
    let co270 = rotate_cw90(&co180);
    let ci90 = rotate_cw90(&ci);
    let ci180 = rotate_cw90(&ci90);
    let ci270 = rotate_cw90(&ci180);

    let mut mask = get_tile_mask_arr(full_tile);

    // Edge half-pieces
    if w && !n {
        mask = and_mask(mask, &ul);
    }
    if w && !s {
        mask = and_mask(mask, &ll);
    }
    if n && !w {
        mask = and_mask(mask, &ll90);
    }
    if n && !e {
        mask = and_mask(mask, &ul90);
    }
    if e && !n {
        mask = and_mask(mask, &ll180);
    }
    if e && !s {
        mask = and_mask(mask, &ul180);
    }
    if s && !w {
        mask = and_mask(mask, &ul270);
    }
    if s && !e {
        mask = and_mask(mask, &ll270);
    }

    // Outer corners
    if w && n {
        mask = and_mask(mask, &co);
    }
    if n && e {
        mask = and_mask(mask, &co90);
    }
    if e && s {
        mask = and_mask(mask, &co180);
    }
    if s && w {
        mask = and_mask(mask, &co270);
    }

    // Inner corners
    if !w && !n && nw {
        mask = and_mask(mask, &ci);
    }
    if !n && !e && ne {
        mask = and_mask(mask, &ci90);
    }
    if !e && !s && se {
        mask = and_mask(mask, &ci180);
    }
    if !s && !w && sw {
        mask = and_mask(mask, &ci270);
    }

    mask
}

fn water_neighbor_bits(map: &engine::map::game_map::GameMap, coord: MapCoord) -> u8 {
    terrain_neighbor_bits(map, coord, Tiles::Water)
}

fn compute_water_composite(bits: u8) -> WaterMask {
    compute_terrain_composite(
        bits,
        WATER_FULL,
        WATER_SHORE_LL,
        WATER_CORNER_OUTER,
        WATER_CORNER_INNER,
    )
}

fn mountain_neighbor_bits(map: &engine::map::game_map::GameMap, coord: MapCoord) -> u8 {
    terrain_neighbor_bits(map, coord, Tiles::Mountain)
}

fn compute_mountain_composite(bits: u8) -> WaterMask {
    compute_terrain_composite(
        bits,
        MOUNTAIN_FULL,
        MOUNTAIN_SHORE_LL,
        MOUNTAIN_CORNER_OUTER,
        MOUNTAIN_CORNER_INNER,
    )
}
fn mask_pixel(mask: &[u8], x: usize, y: usize) -> bool {
    let bit = y * TILESET_TILE_W + x;
    (mask[bit / 8] >> (7 - bit % 8)) & 1 != 0
}

fn draw_grass_sprite<D, C>(display: &mut D, top_left: Point, mask: &[u8], color: C)
where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let mut pixels = vec![];
    for src_y in 0..TILESET_TILE_H {
        let dy_start = (src_y * TILE_HEIGHT as usize / TILESET_TILE_H) as i32;
        let dy_end = ((src_y + 1) * TILE_HEIGHT as usize / TILESET_TILE_H) as i32;
        for src_x in 0..TILESET_TILE_W {
            if !mask_pixel(mask, src_x, src_y) {
                continue;
            }
            let dx_start = (src_x * TILE_WIDTH as usize / TILESET_TILE_W) as i32;
            let dx_end = ((src_x + 1) * TILE_WIDTH as usize / TILESET_TILE_W) as i32;
            for dy in dy_start..dy_end {
                for dx in dx_start..dx_end {
                    pixels.push(Pixel(top_left + Point::new(dx, dy), color));
                }
            }
        }
    }
    halt_on_error(display.draw_iter(pixels));
}

/// Shared rendering geometry for the gameplay map view.
#[derive(Clone, Copy)]
pub struct RenderConfig {
    /// Header band height in pixels.
    pub header_height: u32,
    /// Footer band height in pixels.
    pub footer_height: u32,
}

/// Shared theme colors for gameplay rendering.
#[derive(Clone, Copy)]
pub struct MapViewTheme<C>
where
    C: PixelColor + Copy,
{
    /// Background fill color.
    pub background: C,
    /// HUD text color.
    pub text: C,
    /// Selected hero marker color.
    pub selected_hero: C,
    /// Unselected hero marker color.
    pub hero: C,
    /// Enemy spawn marker color.
    pub enemy_spawn: C,
    /// Chest marker color.
    pub chest: C,
    /// Converts tile terrain into a device color.
    pub tile_color: fn(Tiles) -> C,
    /// Converts tile terrain into the sprite overlay color (drawn on top of the base fill).
    pub tile_sprite_color: fn(Tiles) -> C,
    /// Converts team id into a device color.
    pub team_color: fn(usize) -> C,
    /// Cursor highlight border color.
    pub cursor: C,
}

/// Shared theme colors for splash rendering.
#[derive(Clone, Copy)]
pub struct SplashTheme<C>
where
    C: PixelColor + Copy,
{
    /// Full-screen background color.
    pub background: C,
    /// Main title/body text color.
    pub text: C,
}

/// Shared theme colors for list-screen rendering.
#[derive(Clone, Copy)]
pub struct ListTheme<C>
where
    C: PixelColor + Copy,
{
    /// Background fill color.
    pub background: C,
    /// Main text color.
    pub text: C,
    /// Highlight fill for the selected row.
    pub selected_fill: C,
}

/// Shared theme colors for save-overlay rendering.
#[derive(Clone, Copy)]
pub struct SaveOverlayTheme<C>
where
    C: PixelColor + Copy,
{
    /// Background fill color.
    pub panel_fill: C,
    /// Border stroke color.
    pub panel_stroke: C,
    /// Main text color.
    pub text: C,
    /// Highlight fill for selected rows.
    pub selected_fill: C,
}

/// Shared theme colors for info-overlay rendering.
#[derive(Clone, Copy)]
pub struct InfoOverlayTheme<C>
where
    C: PixelColor + Copy,
{
    /// Background fill color.
    pub panel_fill: C,
    /// Border stroke color.
    pub panel_stroke: C,
    /// Main text color.
    pub text: C,
}

/// Shared theme colors for end-turn confirmation overlay rendering.
#[derive(Clone, Copy)]
pub struct EndTurnOverlayTheme<C>
where
    C: PixelColor + Copy,
{
    /// Background fill color.
    pub panel_fill: C,
    /// Border stroke color.
    pub panel_stroke: C,
    /// Main text color.
    pub text: C,
    /// Highlight fill for the selected button.
    pub selected_fill: C,
}

/// Cached state used to avoid redrawing unchanged map cells.
#[derive(Default)]
pub struct RenderCache {
    map_view: Option<MapViewCache>,
    /// Lazily-computed composite water masks keyed by 8-bit neighbor pattern.
    water_masks: Vec<Option<WaterMask>>,
    /// Lazily-computed composite mountain masks keyed by 8-bit neighbor pattern.
    mountain_masks: Vec<Option<WaterMask>>,
}

fn cached_water_mask(water_masks: &mut Vec<Option<WaterMask>>, bits: u8) -> WaterMask {
    if water_masks.is_empty() {
        *water_masks = vec![None; 256];
    }
    let idx = bits as usize;
    if let Some(m) = water_masks.get(idx).copied().flatten() {
        return m;
    }
    let m = compute_water_composite(bits);
    water_masks[idx] = Some(m);
    m
}

fn cached_mountain_mask(mountain_masks: &mut Vec<Option<WaterMask>>, bits: u8) -> WaterMask {
    if mountain_masks.is_empty() {
        *mountain_masks = vec![None; 256];
    }
    let idx = bits as usize;
    if let Some(m) = mountain_masks.get(idx).copied().flatten() {
        return m;
    }
    let m = compute_mountain_composite(bits);
    mountain_masks[idx] = Some(m);
    m
}

/// Shared cache used by the top-level screen renderer.
#[derive(Default)]
pub struct AppRenderCache {
    map_view: RenderCache,
    overlay_visible: bool,
}

struct MapViewCache {
    map_name: String,
    map_width: usize,
    map_height: usize,
    visible_cols: usize,
    visible_rows: usize,
    view_x: usize,
    view_y: usize,
    cursor_x: isize,
    cursor_y: isize,
    visible_cells: Vec<u32>,
}

/// Returns the visible map window dimensions in tiles for the given screen.
///
/// # Arguments
/// * `screen_size` - Full drawable screen size in pixels.
/// * `config` - Map-view rendering geometry.
pub fn visible_tiles(screen_size: Size, config: RenderConfig) -> (usize, usize) {
    let usable_height =
        screen_size.height.saturating_sub(config.header_height + config.footer_height);
    (
        screen_size.width.saturating_div(TILE_WIDTH) as usize,
        usable_height.saturating_div(TILE_HEIGHT) as usize,
    )
}

/// Clears the gameplay render cache so the next frame repaints everything.
pub fn reset_cache(render_cache: &mut RenderCache) {
    render_cache.map_view = None;
}

/// Shared theme bundle for all top-level screens.
#[derive(Clone, Copy)]
pub struct AppTheme<C>
where
    C: PixelColor + Copy,
{
    /// Splash-screen colors.
    pub splash: SplashTheme<C>,
    /// Shared list colors.
    pub list: ListTheme<C>,
    /// Shared gameplay colors.
    pub map_view: MapViewTheme<C>,
    /// Shared save-overlay colors.
    pub save_overlay: SaveOverlayTheme<C>,
    /// Shared info-overlay colors.
    pub info_overlay: InfoOverlayTheme<C>,
}

/// Draws the current shared top-level app screen.
///
/// # Arguments
/// * `display` - Platform draw target.
/// * `screen_size` - Full drawable screen size in pixels.
/// * `screen` - Shared current screen state.
/// * `render_cache` - Shared app render cache.
/// * `config` - Shared map-view geometry.
/// * `theme` - Device-specific color bundle.
/// * `list_rows` - Number of visible rows in selector screens.
/// * `save_rows` - Number of visible rows in the save overlay load-list.
pub fn draw_app_screen<D, C>(
    display: &mut D,
    screen_size: Size,
    screen: &AppScreen,
    render_cache: &mut AppRenderCache,
    config: RenderConfig,
    theme: AppTheme<C>,
    list_rows: usize,
    save_rows: usize,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    match screen {
        AppScreen::Splash(splash) => {
            reset_cache(&mut render_cache.map_view);
            render_cache.overlay_visible = false;
            draw_splash_screen(
                display,
                screen_size,
                splash,
                APP_TITLE,
                &SPLASH_OPTIONS,
                SPLASH_FOOTER,
                theme.splash,
            );
        }
        AppScreen::MapSelect(map_select) => {
            reset_cache(&mut render_cache.map_view);
            render_cache.overlay_visible = false;
            draw_list_screen(
                display,
                screen_size,
                map_select,
                MAP_LIST_TITLE,
                MAP_LIST_FOOTER,
                list_rows,
                theme.list,
            );
        }
        AppScreen::SaveSelect(save_select) => {
            reset_cache(&mut render_cache.map_view);
            render_cache.overlay_visible = false;
            draw_list_screen(
                display,
                screen_size,
                save_select,
                SAVE_LIST_TITLE,
                SAVE_LIST_FOOTER,
                list_rows,
                theme.list,
            );
        }
        AppScreen::MapView(map_view) => {
            draw_app_map_view(
                display,
                screen_size,
                map_view.as_ref(),
                render_cache,
                config,
                theme,
                save_rows,
            );
        }
    }
}

fn draw_app_map_view<D, C>(
    display: &mut D,
    screen_size: Size,
    map_view: &MapViewScreen,
    render_cache: &mut AppRenderCache,
    config: RenderConfig,
    theme: AppTheme<C>,
    save_rows: usize,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let overlay_visible = map_view.info_overlay.is_some()
        || map_view.save_overlay.is_some()
        || map_view.end_turn_overlay.is_some();
    if render_cache.overlay_visible != overlay_visible {
        reset_cache(&mut render_cache.map_view);
        render_cache.overlay_visible = overlay_visible;
    }

    draw_map_view(
        display,
        screen_size,
        &map_view.app,
        &mut render_cache.map_view,
        config,
        theme.map_view,
    );

    if let Some(end_turn) = &map_view.end_turn_overlay {
        let end_turn_theme = EndTurnOverlayTheme {
            panel_fill: theme.save_overlay.panel_fill,
            panel_stroke: theme.save_overlay.panel_stroke,
            text: theme.save_overlay.text,
            selected_fill: theme.save_overlay.selected_fill,
        };
        draw_end_turn_overlay(display, screen_size, end_turn, end_turn_theme);
    } else if let Some(save_overlay) = &map_view.save_overlay {
        draw_save_overlay(display, screen_size, save_overlay, theme.save_overlay, save_rows);
    } else if let Some(info_overlay) = &map_view.info_overlay {
        draw_info_overlay(display, screen_size, info_overlay, theme.info_overlay);
    }
}

/// Draws a shared splash screen with a centered title and menu.
///
/// # Arguments
/// * `display` - Platform draw target.
/// * `screen_size` - Full drawable screen size in pixels.
/// * `splash` - Splash-screen state.
/// * `title` - Main centered title.
/// * `menu` - Menu labels to render under the title.
/// * `footer` - Footer hint line.
/// * `theme` - Device-specific splash colors.
pub fn draw_splash_screen<D, C>(
    display: &mut D,
    screen_size: Size,
    splash: &SplashScreen,
    title: &str,
    menu: &[&str],
    footer: &str,
    theme: SplashTheme<C>,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    halt_on_error(display.clear(theme.background));

    let title_style =
        MonoTextStyle::new(&embedded_graphics::mono_font::ascii::FONT_10X20, theme.text);
    let body_style = MonoTextStyle::new(&FONT_6X10, theme.text);

    let center_x = (screen_size.width / 2) as i32;
    let center_y = (screen_size.height / 2) as i32;

    halt_on_error(
        embedded_graphics::text::Text::with_alignment(
            title,
            Point::new(center_x, center_y - 24),
            title_style,
            embedded_graphics::text::Alignment::Center,
        )
        .draw(display),
    );

    let menu_top = center_y + 2;
    for (idx, label) in menu.iter().enumerate() {
        let prefix = if idx == splash.selected { ">" } else { " " };
        let line = format!("{prefix} {label}");
        halt_on_error(
            embedded_graphics::text::Text::with_alignment(
                &line,
                Point::new(center_x, menu_top + (idx as i32 * 14)),
                body_style,
                embedded_graphics::text::Alignment::Center,
            )
            .draw(display),
        );
    }

    halt_on_error(
        embedded_graphics::text::Text::with_alignment(
            footer,
            Point::new(center_x, menu_top + (menu.len() as i32 * 14) + 18),
            body_style,
            embedded_graphics::text::Alignment::Center,
        )
        .draw(display),
    );

    if let Some(status_text) = splash.status.as_deref() {
        halt_on_error(
            embedded_graphics::text::Text::with_alignment(
                status_text,
                Point::new(center_x, screen_size.height as i32 - 14),
                body_style,
                embedded_graphics::text::Alignment::Center,
            )
            .draw(display),
        );
    }
}

/// Draws a shared selectable list screen.
///
/// # Arguments
/// * `display` - Platform draw target.
/// * `screen_size` - Full drawable screen size in pixels.
/// * `list` - Shared list state.
/// * `title` - Title shown at the top.
/// * `footer` - Footer hint line.
/// * `visible_rows` - Number of list rows that fit on screen.
/// * `theme` - Device-specific list colors.
pub fn draw_list_screen<D, C>(
    display: &mut D,
    screen_size: Size,
    list: &ListScreen,
    title: &str,
    footer: &str,
    visible_rows: usize,
    theme: ListTheme<C>,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    halt_on_error(display.clear(theme.background));

    let text_style = MonoTextStyle::new(&FONT_6X10, theme.text);
    let selected_style = PrimitiveStyle::with_fill(theme.selected_fill);
    let line_height: i32 = 14;
    let start_y: i32 = 18;

    halt_on_error(Text::new(title, Point::new(6, 10), text_style).draw(display));

    let end = core::cmp::min(list.scroll + visible_rows, list.entries.len());
    for (row, entry_index) in (list.scroll..end).enumerate() {
        let y = start_y + (row as i32 * line_height);
        if entry_index == list.selected {
            halt_on_error(
                Rectangle::new(Point::new(2, y - 9), Size::new(screen_size.width - 4, 12))
                    .into_styled(selected_style)
                    .draw(display),
            );
        }

        let prefix = if entry_index == list.selected { ">" } else { " " };
        let entry = &list.entries[entry_index];
        let line = format!("{prefix} {} ({}b)", entry.label, entry.meta);
        halt_on_error(Text::new(&line, Point::new(6, y), text_style).draw(display));
    }

    halt_on_error(
        Text::new(footer, Point::new(4, screen_size.height as i32 - 2), text_style).draw(display),
    );

    if let Some(status_text) = list.status.as_deref() {
        halt_on_error(
            Text::new(status_text, Point::new(4, screen_size.height as i32 - 14), text_style)
                .draw(display),
        );
    }
}

/// Draws a shared save/load overlay.
///
/// # Arguments
/// * `display` - Platform draw target.
/// * `screen_size` - Full drawable screen size in pixels.
/// * `overlay` - Save overlay state.
/// * `theme` - Device-specific panel colors.
/// * `visible_rows` - Number of rows visible in the load-list panel.
pub fn draw_save_overlay<D, C>(
    display: &mut D,
    screen_size: Size,
    overlay: &SaveOverlay,
    theme: SaveOverlayTheme<C>,
    visible_rows: usize,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let box_width: u32 = 204;
    let box_height: u32 = 120;
    let origin_x = ((screen_size.width - box_width) / 2) as i32;
    let origin_y = ((screen_size.height - box_height) / 2) as i32;
    let text_style = MonoTextStyle::new(&FONT_6X10, theme.text);
    let selected_style = PrimitiveStyle::with_fill(theme.selected_fill);

    halt_on_error(
        Rectangle::new(Point::new(origin_x, origin_y), Size::new(box_width, box_height))
            .into_styled(PrimitiveStyle::with_fill(theme.panel_fill))
            .draw(display),
    );
    halt_on_error(
        Rectangle::new(Point::new(origin_x, origin_y), Size::new(box_width, box_height))
            .into_styled(PrimitiveStyle::with_stroke(theme.panel_stroke, 1))
            .draw(display),
    );

    match overlay {
        SaveOverlay::Menu { selected, status } => {
            halt_on_error(
                Text::new("Save Menu", Point::new(origin_x + 8, origin_y + 14), text_style)
                    .draw(display),
            );
            let entries = ["Save Game", "Load Game", "Cancel"];
            for (idx, label) in entries.iter().enumerate() {
                let y = origin_y + 36 + (idx as i32 * 14);
                if idx == *selected {
                    halt_on_error(
                        Rectangle::new(
                            Point::new(origin_x + 4, y - 9),
                            Size::new(box_width - 8, 12),
                        )
                        .into_styled(selected_style)
                        .draw(display),
                    );
                }
                let prefix = if idx == *selected { ">" } else { " " };
                let line = format!("{prefix} {label}");
                halt_on_error(
                    Text::new(&line, Point::new(origin_x + 8, y), text_style).draw(display),
                );
            }
            halt_on_error(
                Text::new(
                    "Enter: select  Back: close",
                    Point::new(origin_x + 8, origin_y + 102),
                    text_style,
                )
                .draw(display),
            );
            if let Some(status) = status.as_deref() {
                halt_on_error(
                    Text::new(status, Point::new(origin_x + 8, origin_y + 90), text_style)
                        .draw(display),
                );
            }
        }
        SaveOverlay::SaveName { name, status } => {
            halt_on_error(
                Text::new("Save Name", Point::new(origin_x + 8, origin_y + 14), text_style)
                    .draw(display),
            );
            let name_line = format!("> {name}_");
            halt_on_error(
                Text::new(&name_line, Point::new(origin_x + 8, origin_y + 38), text_style)
                    .draw(display),
            );
            halt_on_error(
                Text::new(
                    "Type name  Enter: save  Back: delete/close",
                    Point::new(origin_x + 8, origin_y + 102),
                    text_style,
                )
                .draw(display),
            );
            if let Some(status) = status.as_deref() {
                halt_on_error(
                    Text::new(status, Point::new(origin_x + 8, origin_y + 74), text_style)
                        .draw(display),
                );
            }
        }
        SaveOverlay::LoadList { list } => {
            halt_on_error(
                Text::new("Load Game", Point::new(origin_x + 8, origin_y + 14), text_style)
                    .draw(display),
            );
            let end = core::cmp::min(list.scroll + visible_rows, list.entries.len());
            for (row, entry_index) in (list.scroll..end).enumerate() {
                let y = origin_y + 34 + (row as i32 * 14);
                if entry_index == list.selected {
                    halt_on_error(
                        Rectangle::new(
                            Point::new(origin_x + 4, y - 9),
                            Size::new(box_width - 8, 12),
                        )
                        .into_styled(selected_style)
                        .draw(display),
                    );
                }
                let prefix = if entry_index == list.selected { ">" } else { " " };
                let line = format!("{prefix} {}", list.entries[entry_index].label);
                halt_on_error(
                    Text::new(&line, Point::new(origin_x + 8, y), text_style).draw(display),
                );
            }
            halt_on_error(
                Text::new(
                    "Up/Down: select  Enter: load  Back: close",
                    Point::new(origin_x + 8, origin_y + 102),
                    text_style,
                )
                .draw(display),
            );
            if let Some(status) = list.status.as_deref() {
                halt_on_error(
                    Text::new(status, Point::new(origin_x + 8, origin_y + 90), text_style)
                        .draw(display),
                );
            }
        }
    }
}

/// Draws a shared informational overlay.
///
/// # Arguments
/// * `display` - Platform draw target.
/// * `screen_size` - Full drawable screen size in pixels.
/// * `overlay` - Informational overlay state.
/// * `theme` - Device-specific panel colors.
pub fn draw_info_overlay<D, C>(
    display: &mut D,
    screen_size: Size,
    overlay: &InfoOverlay,
    theme: InfoOverlayTheme<C>,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let box_width: u32 = 188;
    let box_height: u32 = 92;
    let origin_x = ((screen_size.width - box_width) / 2) as i32;
    let origin_y = ((screen_size.height - box_height) / 2) as i32;
    let text_style = MonoTextStyle::new(&FONT_6X10, theme.text);

    halt_on_error(
        Rectangle::new(Point::new(origin_x, origin_y), Size::new(box_width, box_height))
            .into_styled(PrimitiveStyle::with_fill(theme.panel_fill))
            .draw(display),
    );
    halt_on_error(
        Rectangle::new(Point::new(origin_x, origin_y), Size::new(box_width, box_height))
            .into_styled(PrimitiveStyle::with_stroke(theme.panel_stroke, 1))
            .draw(display),
    );

    halt_on_error(
        Text::new(&overlay.title, Point::new(origin_x + 8, origin_y + 14), text_style)
            .draw(display),
    );

    for (index, line) in overlay.lines.iter().enumerate() {
        let y = origin_y + 34 + (index as i32 * 14);
        halt_on_error(Text::new(line, Point::new(origin_x + 8, y), text_style).draw(display));
    }

    halt_on_error(
        Text::new(&overlay.footer, Point::new(origin_x + 8, origin_y + 74), text_style)
            .draw(display),
    );
}

/// Draws the end-of-turn confirmation overlay.
///
/// # Arguments
/// * `display` - Platform draw target.
/// * `screen_size` - Full drawable screen size in pixels.
/// * `overlay` - End-turn overlay state.
/// * `theme` - Device-specific panel colors.
pub fn draw_end_turn_overlay<D, C>(
    display: &mut D,
    screen_size: Size,
    overlay: &EndTurnOverlay,
    theme: EndTurnOverlayTheme<C>,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let box_width: u32 = 180;
    let box_height: u32 = 80;
    let origin_x = ((screen_size.width - box_width) / 2) as i32;
    let origin_y = ((screen_size.height - box_height) / 2) as i32;
    let text_style = MonoTextStyle::new(&FONT_6X10, theme.text);
    let selected_style = PrimitiveStyle::with_fill(theme.selected_fill);

    halt_on_error(
        Rectangle::new(Point::new(origin_x, origin_y), Size::new(box_width, box_height))
            .into_styled(PrimitiveStyle::with_fill(theme.panel_fill))
            .draw(display),
    );
    halt_on_error(
        Rectangle::new(Point::new(origin_x, origin_y), Size::new(box_width, box_height))
            .into_styled(PrimitiveStyle::with_stroke(theme.panel_stroke, 1))
            .draw(display),
    );

    halt_on_error(
        Text::new("End your turn?", Point::new(origin_x + 8, origin_y + 14), text_style)
            .draw(display),
    );

    let labels = ["Yes", "Cancel"];
    for (idx, label) in labels.iter().enumerate() {
        let x = origin_x + 8 + (idx as i32) * 80;
        let y = origin_y + 40;
        if idx == overlay.selected {
            halt_on_error(
                Rectangle::new(Point::new(x, y - 9), Size::new(60, 14))
                    .into_styled(selected_style)
                    .draw(display),
            );
        }
        let prefix = if idx == overlay.selected { ">" } else { " " };
        let line = format!("{prefix} {}", label);
        halt_on_error(Text::new(&line, Point::new(x + 4, y + 3), text_style).draw(display));
    }

    halt_on_error(
        Text::new(
            "Enter: confirm  Esc: cancel",
            Point::new(origin_x + 8, origin_y + 66),
            text_style,
        )
        .draw(display),
    );
}

/// Draws the shared gameplay map view.
///
/// # Arguments
/// * `display` - Platform draw target.
/// * `screen_size` - Full drawable screen size in pixels.
/// * `map_view` - Shared gameplay state.
/// * `render_cache` - Incremental render cache.
/// * `config` - Geometry settings for the device.
/// * `theme` - Device-specific colors.
pub fn draw_map_view<D, C>(
    display: &mut D,
    screen_size: Size,
    map_view: &MapViewApp,
    render_cache: &mut RenderCache,
    config: RenderConfig,
    theme: MapViewTheme<C>,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let text_style = MonoTextStyle::new(&FONT_6X10, theme.text);
    let header = map_view.session().summary();
    let origin_x = 0i32;
    let origin_y = config.header_height as i32;
    let (visible_cols, visible_rows) = visible_tiles(screen_size, config);
    let map = &map_view.session().state().map;
    let map_width = map.tile_width() as usize;
    let map_height = map.tile_height() as usize;

    let requires_full_redraw = match render_cache.map_view.as_ref() {
        Some(cache) => {
            cache.map_name != map_view.session().map_name()
                || cache.map_width != map_width
                || cache.map_height != map_height
                || cache.visible_cols != visible_cols
                || cache.visible_rows != visible_rows
                || cache.view_x != map_view.view_x()
                || cache.view_y != map_view.view_y()
                || cache.cursor_x != map_view.cursor_x()
                || cache.cursor_y != map_view.cursor_y()
        }
        None => true,
    };

    if requires_full_redraw {
        halt_on_error(display.clear(theme.background));
        render_cache.map_view = Some(MapViewCache {
            map_name: map_view.session().map_name().to_string(),
            map_width,
            map_height,
            visible_cols,
            visible_rows,
            view_x: map_view.view_x(),
            view_y: map_view.view_y(),
            cursor_x: map_view.cursor_x(),
            cursor_y: map_view.cursor_y(),
            visible_cells: vec![EMPTY_TILE; visible_cols * visible_rows],
        });
    }

    let cache = render_cache.map_view.as_mut().expect("map view cache must exist before drawing");

    clear_band(
        display,
        Rectangle::new(Point::new(0, 0), Size::new(screen_size.width, config.header_height)),
        theme.background,
    );
    halt_on_error(
        Text::new(&header, Point::new(4, config.header_height as i32 - 2), text_style)
            .draw(display),
    );

    for row in 0..visible_rows {
        for col in 0..visible_cols {
            let map_x = map_view.view_x() + col;
            let map_y = map_view.view_y() + row;
            let coord = MapCoord::new(map_x as u32, map_y as u32);
            let cell = if map_x < map_width && map_y < map_height {
                cell_signature(map_view, coord)
            } else {
                EMPTY_TILE
            };
            let cache_index = row * visible_cols + col;
            if cache.visible_cells[cache_index] == cell {
                continue;
            }

            cache.visible_cells[cache_index] = cell;
            let x = origin_x + (col as i32 * TILE_WIDTH as i32);
            let y = origin_y + (row as i32 * TILE_HEIGHT as i32);
            draw_cell(
                display,
                map_view,
                coord,
                Point::new(x, y),
                &mut render_cache.water_masks,
                &mut render_cache.mountain_masks,
                theme,
            );
        }
    }

    // Draw cursor highlight.
    if map_view.cursor_structure().is_some() {
        draw_cursor_rect(display, map_view, config, theme, origin_x, origin_y);
    } else {
        draw_cursor_outline(display, map_view, config, theme, origin_x, origin_y);
    }

    clear_band(
        display,
        Rectangle::new(
            Point::new(0, screen_size.height as i32 - config.footer_height as i32),
            Size::new(screen_size.width, config.footer_height),
        ),
        theme.background,
    );
}

fn draw_cell<D, C>(
    display: &mut D,
    map_view: &MapViewApp,
    coord: MapCoord,
    top_left: Point,
    water_masks: &mut Vec<Option<WaterMask>>,
    mountain_masks: &mut Vec<Option<WaterMask>>,
    theme: MapViewTheme<C>,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let map = &map_view.session().state().map;
    let Ok(tile) = map.get_tile(coord) else {
        return;
    };

    let sprite_w = TILE_WIDTH.saturating_sub(1);
    let sprite_h = TILE_HEIGHT.saturating_sub(1);
    halt_on_error(
        Rectangle::new(top_left, Size::new(sprite_w, sprite_h))
            .into_styled(PrimitiveStyle::with_fill((theme.tile_color)(tile.kind)))
            .draw(display),
    );

    if matches!(tile.kind, Tiles::Meadow) {
        let grass_idx = (coord.x as usize * 31 + coord.y as usize * 17) % GRASS_TILE_COUNT;
        draw_grass_sprite(
            display,
            top_left,
            grass_mask(grass_idx),
            (theme.tile_sprite_color)(tile.kind),
        );
    }

    if matches!(tile.kind, Tiles::Forest) {
        let forest_idx = (coord.x as usize * 31 + coord.y as usize * 17) % FOREST_TILE_COUNT;
        draw_grass_sprite(
            display,
            top_left,
            forest_mask(forest_idx),
            (theme.tile_sprite_color)(tile.kind),
        );
    }

    if matches!(tile.kind, Tiles::Water) {
        draw_water_cell(display, map, coord, top_left, water_masks, theme);
    }

    if matches!(tile.kind, Tiles::Mountain) {
        draw_mountain_cell(display, map, coord, top_left, mountain_masks, theme);
    }

    if let Some(team_id) = map_view.session().state().city_owner(coord) {
        halt_on_error(
            Rectangle::new(top_left + Point::new(1, 1), Size::new(4, 4))
                .into_styled(PrimitiveStyle::with_fill((theme.team_color)(team_id as usize)))
                .draw(display),
        );
    }

    if map.has_enemy_spawn(coord) {
        halt_on_error(
            Rectangle::new(top_left + Point::new(1, 1), Size::new(3, 3))
                .into_styled(PrimitiveStyle::with_fill(theme.enemy_spawn))
                .draw(display),
        );
    }

    if map.has_chest_spawn(coord) {
        let x = top_left.x + TILE_WIDTH as i32 - 5;
        halt_on_error(
            Rectangle::new(Point::new(x, top_left.y + 1), Size::new(3, 3))
                .into_styled(PrimitiveStyle::with_fill(theme.chest))
                .draw(display),
        );
    }

    if let Some(hero) = map_view.session().state().hero_at(coord) {
        draw_hero_marker(
            display,
            hero.get_id(),
            map_view.session().selected_hero_id(),
            top_left,
            theme,
        );
    }
}

fn draw_water_cell<D, C>(
    display: &mut D,
    map: &engine::map::game_map::GameMap,
    coord: MapCoord,
    top_left: Point,
    water_masks: &mut Vec<Option<WaterMask>>,
    theme: MapViewTheme<C>,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let bits = water_neighbor_bits(map, coord);
    let mask = cached_water_mask(water_masks, bits);
    draw_grass_sprite(display, top_left, &mask, (theme.tile_sprite_color)(Tiles::Water));
}

fn draw_mountain_cell<D, C>(
    display: &mut D,
    map: &engine::map::game_map::GameMap,
    coord: MapCoord,
    top_left: Point,
    mountain_masks: &mut Vec<Option<WaterMask>>,
    theme: MapViewTheme<C>,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let bits = mountain_neighbor_bits(map, coord);
    let mask = cached_mountain_mask(mountain_masks, bits);
    draw_grass_sprite(display, top_left, &mask, (theme.tile_sprite_color)(Tiles::Mountain));
}

fn draw_hero_marker<D, C>(
    display: &mut D,
    hero_id: HeroId,
    selected_hero_id: HeroId,
    top_left: Point,
    theme: MapViewTheme<C>,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let color = if hero_id == selected_hero_id { theme.selected_hero } else { theme.hero };
    let mask = tile_atlas_mask(25);
    draw_grass_sprite(display, top_left, mask, color);
}

fn draw_cursor_outline<D, C>(
    display: &mut D,
    map_view: &MapViewApp,
    _config: RenderConfig,
    theme: MapViewTheme<C>,
    origin_x: i32,
    origin_y: i32,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let cursor_x = map_view.cursor_x();
    let cursor_y = map_view.cursor_y();
    let view_x = map_view.view_x() as isize;
    let view_y = map_view.view_y() as isize;
    let rel_x = cursor_x - view_x;
    let rel_y = cursor_y - view_y;
    if rel_x < 0 || rel_y < 0 {
        return;
    }
    let x = origin_x + (rel_x as i32) * TILE_WIDTH as i32;
    let y = origin_y + (rel_y as i32) * TILE_HEIGHT as i32;
    draw_rect_stroke(display, x, y, TILE_WIDTH, TILE_HEIGHT, theme.cursor);
}

fn draw_cursor_rect<D, C>(
    display: &mut D,
    map_view: &MapViewApp,
    _config: RenderConfig,
    theme: MapViewTheme<C>,
    origin_x: i32,
    origin_y: i32,
) where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    if let Some(info) = map_view.cursor_structure() {
        let view_x = map_view.view_x() as isize;
        let view_y = map_view.view_y() as isize;
        let start_x = (info.min_x as isize - view_x) as i32;
        let start_y = (info.min_y as isize - view_y) as i32;
        let end_x = start_x + (info.max_x - info.min_x + 1) as i32;
        let end_y = start_y + (info.max_y - info.min_y + 1) as i32;

        // visible area in tiles
        let visible_cols = 1000i32; // will be clamped by screen below
        let visible_rows = 1000i32;

        if end_x <= 0 || end_y <= 0 || start_x >= visible_cols || start_y >= visible_rows {
            return;
        }

        let clamped_start_x = start_x.max(0);
        let clamped_start_y = start_y.max(0);
        let clamped_end_x = (end_x as i32).min(visible_cols);
        let clamped_end_y = (end_y as i32).min(visible_rows);

        let width = ((clamped_end_x - clamped_start_x).max(0) as u32) * TILE_WIDTH;
        let height = ((clamped_end_y - clamped_start_y).max(0) as u32) * TILE_HEIGHT;

        let x = origin_x + clamped_start_x * TILE_WIDTH as i32;
        let y = origin_y + clamped_start_y * TILE_HEIGHT as i32;

        if width > 0 && height > 0 {
            draw_rect_stroke(display, x, y, width, height, theme.cursor);
        }
    }
}

fn draw_rect_stroke<D, C>(display: &mut D, x: i32, y: i32, width: u32, height: u32, color: C)
where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    let stroke = PrimitiveStyle::with_stroke(color, 2);
    let rect = Rectangle::new(Point::new(x, y), Size::new(width, height)).into_styled(stroke);
    halt_on_error(rect.draw(display));
}

fn cell_signature(map_view: &MapViewApp, coord: MapCoord) -> u32 {
    let map = &map_view.session().state().map;
    let Ok(tile) = map.get_tile(coord) else {
        return EMPTY_TILE;
    };

    let mut signature = tile.kind.to_gid();
    if let Some(hero) = map_view.session().state().hero_at(coord) {
        signature |= (u32::from(hero.get_id()) + 1) << 16;
    }
    if let Some(team_id) = map_view.session().state().city_owner(coord) {
        signature |= (u32::from(team_id) + 1) << 24;
    }
    if map.has_enemy_spawn(coord) {
        signature |= 1 << 30;
    }
    if map.has_chest_spawn(coord) {
        signature |= 1 << 31;
    }
    signature
}

fn clear_band<D, C>(display: &mut D, rect: Rectangle, color: C)
where
    D: DrawTarget<Color = C>,
    C: PixelColor + Copy,
{
    halt_on_error(rect.into_styled(PrimitiveStyle::with_fill(color)).draw(display));
}

fn halt_on_error<T, E>(result: Result<T, E>) -> T {
    match result {
        Ok(value) => value,
        Err(_) => loop {
            core::hint::spin_loop();
        },
    }
}
